# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100


![numpy](https://image.slidesharecdn.com/numpypythoncheatsheet-181227141853/95/numpy-python-cheatsheet-1-638.jpg?cb=1545920343)

In [24]:
# numpy 버전확인
np.__version__

'1.20.1'

## 1. 데이터 생성

In [2]:
import numpy as np  # 관행 상 np 라고 고정

In [4]:
a = np.zeros(3) # 1차원 배열 = 벡터
a

array([0., 0., 0.])

In [4]:
print(a) # 리스트하고 기호가 같아 구분을 신경써야함 -> type() 으로 확인

[0. 0. 0.]


- type()으로 데이터 타입 확인,  dir()로 이용가능한 메소드 등 확인

In [5]:
type(a)
# dir(a)

numpy.ndarray

In [6]:
b = [1,2,3] # 배열이 아닌 리스트 생성

type(b) # [] 리스트

list

## numpy 값 만들기

In [7]:
# 1차원 배열 = 벡터
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [16]:
type(b)
# dir(b)

numpy.ndarray

In [9]:
# 3차원 배열 이상 = 텐서(tensor)
c = np.array([[[1,2],[3,4],[5,6]]]) # []개수가 차원 수
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [20]:
type(c)

numpy.ndarray

### numpy는 **homogeneous**이다. 동종의 데이터만 취급한다.

In [10]:
a = np.array([1,'2',3])
a  # 숫자와 문자 혼용 시 전부 문자열로 변함

array(['1', '2', '3'], dtype='<U11')

In [12]:
b = np.array(['a',1,True])
b # 숫자와, 논리값, 문자 혼용 시 전부 문자열로 변함

array(['a', '1', 'True'], dtype='<U11')

### np.zeros  


메모리를 할당받아 0으로 초기화된 배열을 반환.(<->empty)

In [13]:
# tuple로 인자를 넣으면 그대로 모양을 만든다
# zeros는 0으로 값을 모두 채운다.
a = np.zeros((2,3)) # 2행 3열
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# tuple 대신 int로 넣으면 벡터로 모양을 만든다.
# dtype의 기본값은 float 이므로 0. 으로 출력된다.
b = np.zeros(2)
b

array([0., 0.])

### np.eye  
자유로운 모양의 단위행렬 만들 때 사용

In [15]:
# 숫자만 사용할 수 있다.
a = np.eye(3)  # 3행 3열로 생성
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 행과 열 따로 지정 가능
b = np.eye(3, 2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [17]:
# k=1 을 지정하면 1이 채워지는 자리가 0번이 아니라 1번부터 채워진다
# 다른 숫자로 다른 자리 지정 가능
c = np.eye(3, 4, k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity  
np.eye와 비슷하지만 int 값 하나만 지정해 기본적인 단위행렬만 생성 가능

In [18]:
# 단위행렬 : identity matrix
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full

In [20]:
# 행렬 지정, 모두 채울 값 지정
a = np.full((2,2),1)
a

array([[1, 1],
       [1, 1]])

In [3]:
b = np.full(3,4)
b

array([4, 4, 4])

In [4]:
# 채울값에 맞춰 열 개수 지정하면 맞춰서 채워준다.
c = np.full((1,2),[1,2])
c

array([[1, 2]])

In [5]:
d = np.full((2,2),[1,2])
d

array([[1, 2],
       [1, 2]])

In [6]:
e = np.full((1,3),[1,2,3])
e

array([[1, 2, 3]])

In [7]:
f = np.full((2,3),[1,2,3])
f

array([[1, 2, 3],
       [1, 2, 3]])

### np.empty  

메모리 할당만 받고 초기화 없이 반환한다.  
즉, empty함수를 실행할 때마다 값이 다르다.  
해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이 그대로 영역의 주소만 알려줄 뿐, 초기화는 사용자에게 맡기기 때문.

이미 행렬을 지정했으면 뒤에 np.empty로 행렬을 지정해도 원래 지정한 행렬 불러옴  

In [13]:
# random 값으로 1행 3열 생성
a = np.empty(shape=(10,), dtype=np.int8)
a

array([48, 91, 61, 54, 32,  2,  0,  0,  0,  0], dtype=int8)

In [14]:
m = np.zeros((3,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
m = np.empty((3,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones  
형태를 지정해 1로 다 채운다.

In [16]:
a = np.ones(3)
a

array([1., 1., 1.])

In [17]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
c = np.ones([3,4])

In [99]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
# np.empty
# 앞에서 생성한 값을 지정 안하는 행렬의 크기가 있으면 그대로 복사해서 사용함
d = np.empty((3,4))

In [103]:
# np.full 과 같이 값을 지정하는 행렬은 안가져옴
# np.zeros np.identity 와 같이 알아서 내용물 생성하는거만 그대로 가져옴
d 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### _like

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
a.shape

(2, 3)

In [143]:
# 기존에 생성된 배열의 크기를 참조해서 새로운 배열 생성
# empty는 원래 난수값 생성
# 연산하기 위해서  shape를 맞춰야하는 경우가 있다.
b = np.empty_like(a)

In [144]:
b

array([[    98,    414,      0],
       [     0, 131074,      0]])

In [22]:
a = np.eye(2)
a.shape

(2, 2)

In [23]:
b = np.eye(3)
b.shape

(3, 3)

In [151]:
a+b # shape이 안맞아서 연산 불가

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

### np.linspace(start, stop, num, endpoint, restep, dtype)

배열에 생성될 멤버의 갯수로 각 값의 편차에 맞춰 배열을 생성

In [25]:
# 같은 간격으로 0부터 49까지 50개 생성
# 세번째 인자가 num 
a = np.linspace(0,49) # default num = 50
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [156]:
# 1부터 10 까지 3개의 요소를 생성
# default   endpoint = True 로 설정되어 있기 때문에 10 포함
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [158]:
# 1부터 10미만 사이에서 3개의 요소를 생성
np.linspace(1,10, 3, endpoint = False)

array([1., 4., 7.])

### np.logspace(start, stop, num, endpoint, base, dtype)

로그 스케일 값으로 배열을 만든다.

In [33]:
# linspace와 비슷하다.
# log scale을 사용하는 차이
# 1부터 50까지 사이의 10개의 요소를 생성한다.
a = np.logspace(1, 50, 10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

## dtype : 데이터 타입

numpy는 c를 기반으로 해서 만들었기 때문에 C의 데이터 타입을 차용할 수 있다.

In [34]:
a = np.array([1,2,3], dtype = np.int8)
a

array([1, 2, 3], dtype=int8)

In [166]:
type(a)

numpy.ndarray

In [167]:
type(a[0])

numpy.int8

In [35]:
# np.int8 은 -128 ~ 127 사이의 값을 저장할 수 있다.
# 2^8 = 256개
# 범위를 벗어나면 쓰레기 값 나옴
b
b = np.array([129, 128, 127, 2, 3, -127, -128, -129], dtype=np.int8)
b

array([-127, -128,  127,    2,    3, -127, -128,  127], dtype=int8)

In [181]:
type(b[0])

numpy.int8

In [36]:
# int는 python의 int를 사용한다.
# 즉, python의 int는 numpy의 int32와 같다
c = np.array([127, 2, 3, -127, -128], dtype = int)
c

array([ 127,    2,    3, -127, -128])

In [184]:
type(c[0])

numpy.int32

In [37]:
# 데이터타입을 문자열 형태로 자유형으로 선언 가능
d = np.array([267, 8, 4], dtype = 'i8')
d

array([267,   8,   4], dtype=int64)

In [197]:
type(d[0])

numpy.int64

- array의 정보를 알려주는 함수들

In [42]:
a = np.array([[1,2,3],[4,5,6]])

In [43]:
# array의 shape을 알려준다
a.shape

(2, 3)

In [44]:
# array의 차원을 알려준다
a.ndim

2

In [45]:
# array의 데이터타입을 알려준다
a.dtype

dtype('int32')

In [204]:
# 요소의 개수를 알려준다
# shape만 있으면 알 수 있다.
a.size

6

In [207]:
# 요소당 byte수를 알려준다
# 1byte = 8bit
# 8bit * 4  = 32 dtype
a.itemsize

4

## numpy와  python의 속도 차이

In [210]:
np.arange(10) # 연속된 값이 들어간 array 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

값이 작을때는 속도가 비슷하다.  
값이 커지면 속도 차이가 난다. 값이 커지면 overflow가 발생해 값은 다를 수도 있다.

In [218]:
# numpy를 이용한 계산
%time np.sum(np.arange(100000000)) # 계산이 훨씬 빠르다

Wall time: 470 ms


887459712

In [216]:
# pyhon을 이용한 계산
%time sum(range(100000000))

Wall time: 5.66 s


4999999950000000

같은 np.sum() 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [220]:
%time np.sum(np.arange(100000000)) # 훨씬 빠르다

Wall time: 388 ms


887459712

In [221]:
%time np.sum(range(100000000))

Wall time: 43.5 s


887459712

## copy

In [ ]:
#대입문 6가지
a = 1
a = b = 1  # a = b = [1.2.3]  이렇게 mutable을 여러 변수에 할당할 때는 조심해야함.
           # 만약 b를 변경하면 같은 주소를 공유하는 a도 변경되기 때문 
a,b = 1,2
a, *b = 1,2,3
a += 1  # a = a + 1
global, nonlocal

### - python에서 copy

In [222]:
a = [1,2,3] # list 는 heterogeneous  sequence  mutable

In [223]:
b = a

In [224]:
b

[1, 2, 3]

In [226]:
a is b  # is 는 메모리 주소를 비교

True

In [227]:
a == b # 값을 비교

True

In [228]:
b[0] = 7

In [229]:
b

[7, 2, 3]

In [230]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a도 같이 변경이 된다.
a

[7, 2, 3]

### - copy()

In [51]:
a = [1,2,3]

In [52]:
# copy() 함수를 사용하면 똑값은 값만 가지고 메모리는 공유하지 않음
b = a.copy()  # a의 값을 새로운 메모리에 저장

In [53]:
a is b

False

In [235]:
id(a)

1781810706176

In [236]:
id(b)

1781810707136

In [54]:
# 값은 같다
a == b

True

In [238]:
b[0] =7

In [239]:
# 1차원 리스트인 경우 알아서 deep copy가 됨
# a는 안바뀐다
print(a)
print(b)

[1, 2, 3]
[7, 2, 3]


### - shallow copy  
copy시 주소는 다르지만 값을 변경하면 같이 바뀐다.

In [55]:
a = [[1,2,3]]

In [56]:
b = a.copy()

In [57]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [58]:
b[0][0] = 7

In [59]:
# 2차원 이상이면 copy 함수를 호출해 쓰더라도 a가 바뀐다
print(a)
print(b)

[[7, 2, 3]]
[[7, 2, 3]]


In [60]:
# 주소 다름
a is b

False

In [248]:
# 같이 바껴서 값 같음
a[0] is b[0]

True

### - deepcopy  

주소 다름  
2차원 이상이어도 b값을 바꾸면 a값 안바뀌게 한다 

In [249]:
import copy

In [250]:
a = [[1,2,3]]

In [251]:
b = copy.deepcopy(a)

In [253]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [254]:
a is b

False

In [255]:
# deep copy가 되서 아예 값, 메모리 다르다
a[0] is b[0]

False

- 1차원 list 일때 slice 로 copy하면 deep copy

:  전체를 의미  

슬라이싱 방식으로 1차원 리스트일때는 재할당하면 deepcopy가 된다.   


In [256]:
a = [1,2,3]

In [257]:
# slice 로 전체 복사
b = a[:]

In [258]:
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [259]:
b[0] = 7

In [260]:
# deep copy되서 원본 안바뀜
print(a)
print(b)

[1, 2, 3]
[7, 2, 3]


- 2차원 이상 list에서 slice로 copy를 하면 shallow copy(얇은copy)가 이루어진다

In [261]:
a = [[1,2,3]]

In [262]:
b = a[:]

In [263]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [264]:
a is b # 주소는 다르고

False

In [265]:
a[0] is b[0] # 값은 같다

True

## numpy의 copy

In [276]:
a = b = np.array([1,2,3])

In [267]:
a is b

True

array는 sequecnce타입으로 인덱싱과 슬라이싱이 가능하다.

In [268]:
a[0] # indexing

1

In [269]:
a[:] # slicing

array([1, 2, 3])

array는 mutable 이다.  
예외가 몇가지 있지만 기본적으로 mutable에 가깝다.

In [277]:
a[0] = 100

In [278]:
a

array([100,   2,   3])

In [280]:
# a = b 같은 주소 할당해서 같이 변한다
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous이다.

In [272]:
c = np.array([1, 'a', True])

In [273]:
c

array(['1', 'a', 'True'], dtype='<U11')

In [275]:
type(c[0])

numpy.str_

### numpy는 기본적으로 deepcopy여서 copy()함수 사용하게 되면 deepcopy가 이루어진다

#### python의 copy는 기본적으로 shallow이다.

In [285]:
a = np.array([[1,2,3]])

In [286]:
b = a.copy()

In [287]:
a is b # 주소 다름

False

In [289]:
b[0][0] = 7

In [290]:
# 주소 다르니까 같이 안변함
print(a)
print(b)

[[1 2 3]]
[[7 2 3]]


## 다른 데이터 타입에서 데이터 가져오기

#### as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붕는다.

In [292]:
# python의 list 데이터 타입을 int ndarray로 변환
a = [1,2,3]
print(type(a)) # list
print(type(a[0]))
b = np.array(a)
print(type(b)) # array 배열
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [293]:
# python의 list 데이터 타입을 float ndarry로 변환
a = [1,2,3]
print(type(a)) 
print(type(a[0]))
b = np.asfarray(a)
print(type(b)) 
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [297]:
# python의 list 데이터 타입 float이면 float ndarray로 변환
# python의 list 데이터 타입 int이면 int ndarry로 변환
a = [1.,2.,3.]
print(type(a)) 
print(type(a[0]))
b = np.asarray(a)
print(type(b)) 
print(type(b[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [296]:
a = [1.,2.,3.]
print(type(a)) 
print(type(a[0]))
b = np.asfarray(a)
print(type(b)) 
print(type(b[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


numpy의 as계열과 from계열은 약간 비체계적인 면이 있기 때문에 tensorflow에서는 조금다르게 사용한다.  

--------------------
 numpy에서 데이터 만드는 방법 정리  
 - 생성
  - factory method계열
    zeros, ones, arrange, eye, identity, empty
 - 기반
  - array, as계열, from계열, _like계열
 - load
  - 파일로부터 값을 가져오는 방법

## 값 가져오기

1. comma로 값 가져오기

In [298]:
a = [[1,2,3],[4,5,6]] # python
b = np.array([[1,2,3],[4,5,6]])  # numpy

In [299]:
a[0,1] # slicing은 되는데 ,안됨

TypeError: list indices must be integers or slices, not tuple

In [301]:
a[0] # 1차원 리스트로 가져옴

[1, 2, 3]

In [305]:
# comma를 사용하려면 slice객체를 이용해야함.
a[slice(0,2)] # 2차원 리스트로 가져옴. 0행 이상 2행 미만

[[1, 2, 3], [4, 5, 6]]

- numpy는 기본적으로 인덱싱/슬라이싱할때 comma를 사용할 수 있다.

In [308]:
# numpy
# 배열 b[행,열]
print(b[0,2])
print(b[0,-1])

3
3


In [306]:
print(a) # list
print(b) # array

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [307]:
# python일 때 
# 리스트 a[행][열]
print(a[0][2])

3


### 2. boolean indexing

In [312]:
# python list
a = [[1,2,3,4]]

In [313]:
a >2  # list는 안됨

TypeError: '>' not supported between instances of 'list' and 'int'

arrray를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)

In [65]:
# 원소별로 각각 비교를 해서 논리값으로 리턴
# numpy에서는 가능하고 python에서는 안된다.
b = np.array([[1,2,3,4]])
b>2

array([[False, False,  True,  True]])

numpy는 indexing, slicing 자리에 조건도 쓸 수 있다.    
True에 해당되는 값만 가져온다

In [324]:
# 논리값을 줘서 인덱싱한다
b[np.array([[False, False,  True,  True]])]  # b[[1,2,3,4]]

array([3, 4])

In [325]:
# 결과 똑같다
# 즉, 일일이 지정안하고 간단하게 쓸 수 있다
b[b>2]

array([3, 4])

### numpy에서 boolean indexing 조건  
- array만 된다.
- numpy True, False로만 구성되어야 한다.
- shape이 맞아야 한다.(개수가 맞을때만 사용할 수 있다.)

In [328]:
# python 에서는 지원안한다.
a = [[1,2,3,4]]
a[[[True,True,False,True]]]

TypeError: list indices must be integers or slices, not list

In [329]:
# 데이터타입 boolean
np.array([[True, False, True, False]]).dtype

dtype('bool')

In [67]:
b = np.array([[1,2,3],[4,5,6]])
# type(b) : python에서 재공하는 내장메소드(스페셜메소드 기본메소드)
b.__class__

numpy.ndarray

In [336]:
b.shape

(2, 3)

In [337]:
b.__getitem__(0) # 0행의 데이터 가져옴

array([1, 2, 3])

In [340]:
b[0]

array([1, 2, 3])

In [338]:
b.__getitem__(1) # 1행의 데이터

array([4, 5, 6])

In [341]:
b[1]

array([4, 5, 6])

In [339]:
b.__getitem__((0,1)) # 튜플로 넣어야함. 0행 1열 데이터 가져옴

2

In [342]:
b[0,1]

2

### 3. fancy indexing

In [346]:
b = np.arange(100).reshape(20,5) # reshape(행,열) 배열의 구조를 변경할때 사용하는 메소드
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

인덱싱, 슬라이싱 자리에 괄호를 하나 더 넣으면 fancy indexing 할 수 있다.  
여러개를 한번에 인덱싱할 수 있다.

In [349]:
b[:] # 전체를 가져온다. = b[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [352]:
b[1:3] # 1행부터 3행 미만의 데이터 가져온다

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [353]:
b[1:3, 2:4] # 1행부터 3행 미만이면서 2열부터 4열 미만의 데이터

array([[ 7,  8],
       [12, 13]])

In [354]:
b[[1,3,5]] # 1, 3, 5 행의 데이터

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [355]:
b[[1,3,5],[0,2,4]] # (1,0) (3,2) (5,4)의 데이터

array([ 5, 17, 29])

- fancying indexing은 인덱싱 기법만 사용할 수 있다.  
":"(콜론)은 슬라이싱 기법이므로 지원하지 않는다.

In [356]:
# Error
b[[2:5]]

SyntaxError: invalid syntax (<ipython-input-356-7cf25934e432>, line 2)

In [358]:
b[:,[0,2,4]] # 모든행에서 0, 2, 4열

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39],
       [40, 42, 44],
       [45, 47, 49],
       [50, 52, 54],
       [55, 57, 59],
       [60, 62, 64],
       [65, 67, 69],
       [70, 72, 74],
       [75, 77, 79],
       [80, 82, 84],
       [85, 87, 89],
       [90, 92, 94],
       [95, 97, 99]])

- fancy indexing은 내부적으로 copy해주는 방식이다.  

    deep copy처럼 주소 다르고 값도 안바뀐다

In [359]:
c = b[[1,3,5]] # fancy indexing으로 가져옴

In [361]:
c

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [362]:
c[0][0] = 120

In [363]:
c

array([[120,   6,   7,   8,   9],
       [ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28,  29]])

In [364]:
# b는 안바뀜
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [365]:
b is c # 주소 다름

False